# Generated by Django 4.2.7 on 2025-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Nom du fichier PDF", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Chemin vers le fichier PDF", max_length=500
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL d'origine du PDF (si applicable)",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Texte extrait du PDF", null=True
                    ),
                ),
                (
                    "content_length",
                    models.IntegerField(
                        default=0, help_text="Nombre de caractères du contenu"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Langue détectée",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Thématique principale",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        default="Moyen",
                        help_text="Niveau de confiance de l'analyse",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Résumé généré par IA", null=True
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Taille du fichier en octets"
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(default=0, help_text="Nombre de pages"),
                ),
                (
                    "source_directory",
                    models.CharField(
                        blank=True,
                        help_text="Répertoire source",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="PDF traité avec succès"
                    ),
                ),
                (
                    "is_retained",
                    models.BooleanField(
                        default=False, help_text="PDF marqué comme important"
                    ),
                ),
                (
                    "extraction_success",
                    models.BooleanField(
                        default=False, help_text="Extraction de texte réussie"
                    ),
                ),
                (
                    "analysis_success",
                    models.BooleanField(
                        default=False, help_text="Analyse OpenAI réussie"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Message d'erreur si échec", null=True
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, help_text="Notes de traitement", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de traitement", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Document PDF",
                "verbose_name_plural": "Documents PDF",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="scraper_pdf_languag_d27391_idx"
                    ),
                    models.Index(fields=["theme"], name="scraper_pdf_theme_0a8082_idx"),
                    models.Index(
                        fields=["is_processed"], name="scraper_pdf_is_proc_20d20e_idx"
                    ),
                    models.Index(
                        fields=["source_directory"],
                        name="scraper_pdf_source__3df23a_idx",
                    ),
                ],
            },
        ),
    ]
